import type { NextPage } from 'next';
import Head from 'next/head';
import ToDoContainer from '../components/ToDoContainer';
import { useEffect, useState } from 'react';


const Home: NextPage = () => {

  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
      setIsLoaded(true)
  }, []
  );

  return (
    <div style={{
      background: "linear-gradient(to right, #5433ff, #20bdff, #a5fecb)", 
      height:"100vh",
      display:"flex",
      justifyContent:"center",
      }}>

      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoaded && <ToDoContainer/>}

    </div>
  )
}

export default Home
